### ISSUE TITLE
heeeeelllllllpppppppp

### ISSUE THREAD

**Issue by hackeze** [valentinbreiz/TerrariaVita-Editor#2]

**Comment by hackeze** [comment]
how can i do it without save manager

**Comment by valentinbreiz** [comment]
Why you don't want to use it? It is necessary to dump the save

**Comment by hackeze** [comment]
thankz for replying bro but u see the vpk install launches and every thing
butttttt i fuck my games

**Comment by valentinbreiz** [comment]
I don't understand what is your problem..

**Comment by hackeze** [comment]
the problem is when i try to backup any game save i corubtes my game files

**Comment by hackeze** [comment]
PLS HELP

**Comment by hackeze** [comment]
iam running hencore 3.68

**Comment by valentinbreiz** [comment]
So you should not submit an issue here but here: https://github.com/d3m3vilurr/vita-savemgr/issues

**Comment by hackeze** [comment]
thankz man love u not a homo okay

**Comment by hackeze** [comment]
Hello there,

I just signed the petition "Ubisoft: Galaxy Life back" and wanted to see if
you could help by adding your name.

Our goal is to reach 20,613 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/FtbWBXxRd2

Thanks!
mohamed

**Comment by hackeze** [comment]
yip its closed lol
