### ISSUE TITLE
Cannot save character

### ISSUE THREAD

**Issue by Ravash7** [valentinbreiz/TerrariaVita-Editor#3]
Hello, I'm trying to save my character and I get this error:

![528541e334a4bbb7d5db5144e01ab661](https://user-images.githubusercontent.com/4820355/50455626-83fa7e80-090c-11e9-8662-0996032180bb.png)

How do I fix this?

**Comment by valentinbreiz** [comment]
Hello @Ravash7, sorry for this (too) late response...
Can you give me you save file ?

**Comment by MERLev** [comment]
I have the same issue
You could check character file in attachments
[PLAYER1.ZIP](https://github.com/valentinbreiz/TerrariaVita-Editor/files/4054668/PLAYER1.ZIP)

**Comment by valentinbreiz** [comment]
@MERLev can you try with the new release please ?

**Comment by MERLev** [comment]
@valentinbreiz I could confirm, it's working just fine in a latest update. Thank you sir.
